#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
check_chapter_claims.py  --  ROUND 3 of the chapter self-verification
=====================================================================
Rounds 1 and 2 check that the numbers are right and mutually consistent.  A
chapter can pass both and still be unreproducible, because it points at a
script that was renamed, a state variable that does not exist, or a command
that no longer runs.  Those break the moment a reviewer tries to follow the
chapter, and they are invisible to any check that only reads numbers.

This round follows every executable claim the chapters make:

  A. every file path named in a chapter exists
  B. every "실행: python3 ..." command actually runs and exits 0
  C. every state variable named in prose is declared in the *Depvar block
  D. every UMAT subroutine named in prose exists in the source
  E. the failure-mode evidence quoted from the .msg is quoted verbatim
     consistently across the documents that use it

Run:  python3 verification/check_chapter_claims.py
"""
from __future__ import print_function

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DOCS = os.path.join(ROOT, "docs")
CHAPTERS = ["CH2_LITERATURE_REVIEW.md", "CH3_VERIFICATION.md",
            "CH4_RVE_HOMOGENISATION.md"]

_OK, _BAD = [], []


def check(name, cond, detail=""):
    (_OK if cond else _BAD).append(name)
    print("  %s  %-58s %s" % ("PASS" if cond else "FAIL", name, detail))


def run(cmd):
    p = subprocess.Popen(cmd, cwd=ROOT, shell=True, stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
    out, _ = p.communicate()
    return out.decode("utf-8", "replace"), p.returncode


def main():
    print("=" * 80)
    print("ROUND 3 -- check_chapter_claims.py: are the chapters reproducible?")
    print("=" * 80)

    texts = {}
    for f in CHAPTERS:
        p = os.path.join(DOCS, f)
        if not os.path.exists(p):
            check("%s exists" % f, False)
            return 1
        texts[f] = open(p).read()
    joined = "\n".join(texts.values())

    # ------------------------------------------------------------------ A
    print("\n A. every file named in a chapter resolves to a real file")
    # Any backticked token that looks like a filename -- with or without a
    # directory prefix -- must resolve somewhere in the repo.  This is what
    # catches a renamed script long after the chapter quoted it.
    named = set()
    for t in texts.values():
        named |= set(re.findall(
            r"`([A-Za-z0-9_./\[\]<>*-]+\.(?:py|for|f|sh|inp|csv|md|ori))`", t))
    check("chapters name at least 15 files", len(named) >= 15,
          "%d found" % len(named))

    # Some named files are GENERATED, not committed -- the input decks are
    # 2.5 MB each and live only in dist/.  A generated name is legitimate as
    # long as some generator in the repo actually writes it, so index the
    # generators' source too.  A typo'd deck name still fails, which is the
    # point of the check.
    generated = set()
    for gen in ("abaqus/make_patch_tests.py", "abaqus/make_rve_virtual_tests.py",
                "abaqus/assemble_inp.py", "abaqus/retune_deck.py",
                "abaqus/make_macro_thermalshock.py"):
        gp = os.path.join(ROOT, gen)
        if os.path.exists(gp):
            src = open(gp).read()
            for m in re.findall(r'"([A-Za-z0-9_]+\.inp)"', src):
                generated.add(m)
            for m in re.findall(r'"([A-Za-z0-9_]+)\.inp"', src):
                generated.add(m + ".inp")
            for m in re.findall(r'"([A-Za-z0-9_]+)%d\.inp"', src):
                generated.add(m)

    index = {}
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "__pycache__", "dist")]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            index.setdefault(fn, []).append(full)
            index.setdefault(os.path.relpath(full, ROOT), []).append(full)

    for rel in sorted(named):
        if "<" in rel or "*" in rel:          # generated-name placeholder
            stem = re.split(r"[<*]", rel)[0]
            ok = any(k.startswith(os.path.basename(stem)) for k in index) \
                or any(stem in k for k in index)
            check("%s (pattern)" % rel, ok)
            continue
        base = os.path.basename(rel)
        if rel in index or base in index:
            check(rel, True)
            continue
        gen_ok = base in generated or any(
            base.startswith(g.replace(".inp", "").rstrip("0123456789_"))
            for g in generated)
        check(rel, gen_ok, "generated by a repo script" if gen_ok else "")

    # ------------------------------------------------------------------ B
    print("\n B. every '실행:' command runs and exits 0")
    cmds = set()
    for t in texts.values():
        cmds |= set(re.findall(r"\*\*실행:\*\*\s*`([^`]+)`", t))
        cmds |= set(re.findall(r"(?m)^(python3 [a-z0-9_/.]+\.py[^\n]*)$", t))
        cmds |= set(re.findall(r"(?m)^(bash\s+[a-z0-9_/.]+\.sh[^\n]*)$", t))
    check("chapters quote at least 8 runnable commands", len(cmds) >= 8,
          "%d found" % len(cmds))
    for c in sorted(cmds):
        out, rc = run(c)
        check(c[:56], rc == 0, "" if rc == 0 else "exit %d" % rc)

    # ------------------------------------------------------------------ C
    print("\n C. state variables named in prose are declared in *Depvar")
    dep = open(os.path.join(ROOT, "abaqus", "assemble_inp.py")).read()
    for sdv in sorted(set(re.findall(r"`(SDV\d+|ATEFF|DMACT|EQPS|RMT|DMT|"
                                     r"NCLO|CLOFLG|FITW|FIDC)`", joined))):
        name = sdv if not sdv.startswith("SDV") else sdv
        found = (name in dep
                 or name in open(os.path.join(
                     ROOT, "src", "UMAT_CSIC_THERMSHOCK_V3_0.for")).read()
                 or name in open(os.path.join(
                     ROOT, "postprocess", "homogenize.py")).read())
        check("state variable %s is declared somewhere" % name, found)

    # ------------------------------------------------------------------ D
    print("\n D. UMAT subroutines named in prose exist in the source")
    v3 = open(os.path.join(ROOT, "src",
                           "UMAT_CSIC_THERMSHOCK_V3_0.for")).read()
    v1 = open(os.path.join(ROOT, "src",
                           "UMAT_CSIC_RVE_ZHANG2022_V1_0.for")).read()
    for sub in sorted(set(re.findall(r"`(K[A-Z0-9_]{3,})`", joined))):
        found = ("SUBROUTINE " + sub) in v3 or ("SUBROUTINE " + sub) in v1
        check("SUBROUTINE %s exists" % sub, found)

    # ------------------------------------------------------------------ E
    print("\n E. the .msg evidence is quoted consistently")
    m1 = open(os.path.join(DOCS, "M1_FAILURE_ANALYSIS.md")).read()
    ch3 = texts["CH3_VERIFICATION.md"]
    for tok in ("5.104E-03", "-3.833E-02", "1.709E-09"):
        check("both Ch.3 and the post-mortem quote %s" % tok,
              tok in ch3 and tok in m1)
    check("Ch.3 states the residual moved 7.5x", "7.5" in ch3)
    check("the two documents agree the correction only flipped sign",
          ("부호만" in ch3) and ("same magnitude" in m1 or "opposite" in m1))

    # ------------------------------------------------------------------ F
    print("\n F. no chapter cites a source graded 'secondary'")
    sec = set()
    for csv_name in ("csic_thermal_shock.csv", "failure_criteria.csv",
                     "strength_vs_temperature.csv", "thermal_conductivity.csv"):
        path = os.path.join(ROOT, "data", "literature", csv_name)
        if not os.path.exists(path):
            continue
        for line in open(path):
            if line.startswith("#") or "secondary" not in line:
                continue
            key = line.split(",")[0]
            if key == "NONE":     # a placeholder row meaning "no source at
                continue          # all", not a citation key
            sec.add(key)
    check("secondary-graded keys identified", bool(sec), ", ".join(sorted(sec)))
    for k in sorted(sec):
        n = sum(t.count(k) for t in texts.values())
        check("no chapter cites %s" % k, n == 0,
              "" if n == 0 else "%d mentions" % n)

    print("\n" + "=" * 80)
    if _BAD:
        print("ROUND 3 FAIL -- %d of %d: %s"
              % (len(_BAD), len(_OK) + len(_BAD), ", ".join(_BAD[:5])))
        print("=" * 80)
        return 1
    print("ROUND 3 PASS -- ALL %d EXECUTABLE CLAIMS IN THE CHAPTERS HOLD"
          % len(_OK))
    print("=" * 80)
    return 0


if __name__ == "__main__":
    sys.exit(main())
